-- Create a table for documents
create table if not exists documents (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) not null,
  file_path text not null,
  file_type text not null,
  original_name text not null,
  upload_date timestamp with time zone default timezone('utc'::text, now()) not null,
  extracted_data jsonb, -- Stores the JSON data from Gemini
  internal_ref text, -- Auto-generated by trigger: AC-YYYY-NNNN
  accounting_category text,
  accounting_status text default 'a_saisir' check (accounting_status in ('a_saisir', 'saisi', 'lettre', 'valide')),
  status text default 'pending' check (status in ('pending', 'processing', 'completed', 'error')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table documents enable row level security;

create policy "Users can view their own documents"
  on documents for select
  using (auth.uid() = user_id);

create policy "Users can insert their own documents"
  on documents for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own documents"
  on documents for update
  using (auth.uid() = user_id);

create policy "Users can delete their own documents"
  on documents for delete
  using (auth.uid() = user_id);

-- Storage Bucket Setup (Instructions for User)
-- 1. Create a generic public/private bucket named 'documents'
-- 2. Add RLS policies for storage objects if not creating a public bucket.

-- Storage Policy Example (To be run in SQL Editor of Supabase)
insert into storage.buckets (id, name, public) values ('documents', 'documents', false);

create policy "Authenticated users can upload files"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'documents' AND auth.uid() = owner );

create policy "Users can view their own files"
on storage.objects for select
to authenticated
using ( bucket_id = 'documents' AND auth.uid() = owner );
